# DigitalOcean App Platform spec
# Deploy via: doctl apps create --spec .do/app.yaml
# Or connect the GitHub repo in the DO dashboard and it auto-detects this.

name: stocksense-api
region: nyc

services:
  - name: api
    github:
      repo: <your-github-username>/UGAHacksXI   # ← update with your repo
      branch: main
      deploy_on_push: true
    source_dir: /back-end
    environment_slug: python
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb     # $5/mo basic tier
    http_port: 8080
    run_command: gunicorn --config gunicorn.conf.py app:app
    envs:
      - key: DB_USER
        value: "doadmin"
        scope: RUN_TIME
        type: SECRET
      - key: DB_PASS
        value: "AVNS_E1MUlQ8IweUl4B3L72k"
        scope: RUN_TIME
        type: SECRET
      - key: DB_HOST
        value: "db-mysql-nyc3-02019-do-user-33079250-0.j.db.ondigitalocean.com"
        scope: RUN_TIME
      - key: DB_PORT
        value: "25060"
        scope: RUN_TIME
      - key: DB_NAME
        value: "defaultdb"
        scope: RUN_TIME
      - key: JWT_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: "super-secure-uga-hacks-key"
      - key: GEMINI_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: ""                               # ← paste your key here
      - key: CORS_ORIGINS
        value: "*"
        scope: RUN_TIME
      - key: DB_SSL_MODE
        value: "REQUIRED"
        scope: RUN_TIME
